# Generated by Django 2.1.2 on 2018-11-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbranch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsearch',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
