# Generated by Django 2.1.2 on 2018-11-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbranch', '0002_auto_20181101_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchsearch',
            name='bank',
            field=models.CharField(default='First Bank', max_length=100),
            preserve_default=False,
        ),
    ]
