# Generated by Django 2.2.3 on 2019-08-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankbranch', '0003_branchsearch_bank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BranchSearch',
            new_name='BankBranch',
        ),
    ]
